---
## Github actions update the ATT&CK data every 24hrs
- name: DETTECT - Git clone the DeTTECT repo
  ansible.builtin.git:
    repo: https://github.com/rabobank-cdc/DeTTECT
    dest: "/home/{{ kali_user }}/dettect/"
  changed_when: false

- name: DETTECT - Pull latest DeTTECT Docker image
  community.docker.docker_image:
    name: rabobankcdc/dettect:latest
    source: pull
  register: dettect_image

- name: DETTECT - Create DeTTECT Docker container
  community.docker.docker_container:
    name: dettect
    image: "rabobankcdc/dettect:latest"
    command: /bin/bash
    interactive: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "/home/{{ kali_user }}/dettect/output:/opt/DeTTECT/output"
      - "/home/{{ kali_user }}/dettect/input:/opt/DeTTECT/input"
  changed_when: false

## docker start -i dettect
## python dettect.py editor
