---
- name: DETTECT - Pull latest DeTTECT Docker image
  community.docker.docker_image:
    name: rabobankcdc/dettect:latest
    source: pull
  register: dettect_image

- name: DETTECT - Create DeTTECT Docker container
  community.docker.docker_container:
    name: dettect
    image: "rabobankcdc/dettect:latest"
    command: /bin/bash
    interactive: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "/home/{{ kali_user }}/dettect/output:/opt/DeTTECT/output"
      - "/home/{{ kali_user }}/dettect/input:/opt/DeTTECT/input"
  when: dettect_image.stat.exists == true
  changed_when: false
