---
- name: DIE - Create AppImages directory
  ansible.builtin.file:
    path: /home/{{ kali_user }}/.local/share/appimage/
    state: directory
    owner: "{{ kali_user }}"

- name: DIE - Check that Detect-it-Easy AppImage does not already exist
  ansible.builtin.stat:
    path: /home/{{ kali_user }}/.local/share/appimage/Detect_It_Easy.AppImage
  register: die_appimage_check
  check_mode: false

- name: DIE - Download Detect-it-Easy AppImage
  ansible.builtin.get_url :
    url: https://github.com/horsicq/DIE-engine/releases/download/3.07/Detect_It_Easy-3.07-x86_64.AppImage
    dest: /home/{{ kali_user }}/.local/share/appimage/Detect_It_Easy.AppImage
  when: die_appimage_check.stat.exists == false
  ignore_errors: true

- name: DIE - Make Detect-it-Easy AppImage executable
  ansible.builtin.file:
    path: /home/{{ kali_user }}/.local/share/appimage/Detect_It_Easy.AppImage
    owner: "{{ kali_user }}"
    group: "{{ kali_user }}"
    mode: 'u+x'
