---
- name: DOCKER - Install docker.io package
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: DOCKER - Start and enable docker service
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started
    masked: false
  changed_when: false

- name: DOCKER - Add current user to docker group
  ansible.builtin.user:
    name: "{{ kali_user }}"
    groups: "docker"
    append: true
