---
- name: FIREFOX - Create distribution extensions directory
  ansible.builtin.file:
    path: /usr/share/firefox-esr/distribution/extensions/
    state: directory
    mode: "0655"
    owner: root

- name: FIREFOX - Check that extensions do not already exist
  ansible.builtin.find:
    paths: /usr/share/firefox-esr/distribution/extensions/
    patterns: "*.xpi"
    recurse: no
  register: firefox_addons_check

- name: FIREFOX - Download extension files
  ansible.builtin.uri:
    url: "{{ item.url }}"
    dest: "/tmp/"
  with_items: "{{ firefox_addons }}"
  when: firefox_addons_check == 0

- name: FIREFOX - Copy add-on file to Firefox extensions directory
  ansible.builtin.copy:
    src: "/tmp/{{ item.filename }}"
    dest: "/usr/share/firefox-esr/distribution/extensions/{{ item.uuid }}.xpi"
    mode: "0644"
    owner: root
  with_items: "{{ firefox_addons }}"
  when: firefox_addons_check == 0
