---
## Probably do this with a policy.json file instead
- name: FIREFOX - Download add-on files
  uri:
    url: "{{ item.url }}"
    dest: "/tmp/"
  with_items: "{{ firefox_addons }}"

- name: FIREFOX - Copy add-on file to Firefox extensions directory
  copy:
    src: "/tmp/{{ item.filename }}"
    dest: "/home/{{ kali_user }}/.mozilla/firefox/{{ lookup('env', 'MOZILLA_PROFILE') }}/extensions/{{ item.filename }}"
    mode: "0644"
    owner: "{{ kali_user }}"
  with_items: "{{ firefox_addons }}"
