---
- name: GEM-INSTALL - Check if Ruby installed
  ansible.builtin.apt:
    name: ruby
    state: present
  register: ruby_pkg_status
  check_mode: false

- name: GEM-INSTALL - Install Ruby Gems
  community.general.gem:
    name: "{{ item.name }}"
    state: latest
  when: ruby_pkg_status.changed == false
  with_items: "{{ gem_packages }}"
