---
- name: GEM-INSTALL - Check if Ruby installed
  ansible.builtin.apt:
    name: ruby
    state: present
  check_mode: false

- name: GEM-INSTALL - Install Ruby Gems
  community.general.gem:
    name: "{{ item.name }}"
    state: latest
  with_items: "{{ gem_packages }}"
