---
- name: HAVOC - Install Havoc dependencies
  ansible.builtin.apt:
    name: "{{ havoc_dependencies }}"
    state: present

- name: HAVOC - Git clone the Havoc repo
  ansible.builtin.git:
    repo: https://github.com/HavocFramework/Havoc.git
    dest: /opt/Havoc
  ignore_errors: true

- name: HAVOC - Build the Havoc teamserver
  community.general.make:
    chdir: /opt/Havoc/
    target: ts-build
  changed_when: false
  ignore_errors: true

- name: HAVOC - Build the Havoc client
  community.general.make:
    chdir: /opt/Havoc/
    target: client-build
  changed_when: false
  ignore_errors: true

## Run the Teamserver
## sudo ./havoc server --profile profiles/havoc.yaotl -v --debug
