---
- name: KUBECTL - Create kubectl directory
  ansible.builtin.file:
    path: /usr/share/kubectl
    state: directory

## Should maybe download to /usr/local/bin/
- name: KUBECTL - Download kubectl binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl
    dest: /usr/share/kubectl/
    checksum: "sha256:7fe3a762d926fb068bae32c399880e946e8caf3d903078bea9b169dcd5c17f6d"
    mode: '0755'
    validate_certs: true
