---
- name: KUBECTL - Create kubectl directory
  ansible.builtin.file:
    path: /usr/share/kubectl
    state: directory

## Should maybe download to /usr/local/bin/
- name: KUBECTL - Download kubectl binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl
    dest: /usr/share/kubectl/
    mode: '0755'
  ignore_errors: true
