---
- ansible.builtin.import_tasks: apt-update.yml

- ansible.builtin.import_tasks: apt-install.yml

- ansible.builtin.import_tasks: apt-clean.yml

- ansible.builtin.import_tasks: pip-install.yml

- ansible.builtin.import_tasks: gem-install.yml

- ansible.builtin.import_tasks: docker.yml

- ansible.builtin.import_tasks: dettect.yml

- ansible.builtin.import_tasks: die.yml

- ansible.builtin.import_tasks: ngrok.yml

- ansible.builtin.import_tasks: pulsar.yml

- ansible.builtin.import_tasks: rsactftool.yml

- ansible.builtin.import_tasks: sharpcollection.yml
  when:
    - sharpcollection_enabled | bool

- ansible.builtin.import_tasks: volatility-3.yml
  when:
    - volatility-3_enabled | bool

- ansible.builtin.import_tasks: sagemath.yml
  when:
    - sagemath_enabled | bool

- ansible.builtin.import_tasks: wordlists.yml
