---
- name: MERLIN - Create Merlin directory
  ansible.builtin.file:
    path: /opt/merlin
    state: directory

- name: MERLIN - Check that Merlin server does not already exist
  ansible.builtin.stat:
    path: /opt/merlin/merlinServer-Linux-x64
  register: merlin_check
  check_mode: false

- name: MERLIN - Download Merlin 7z archive
  ansible.builtin.get_url:
    url: https://github.com/Ne0nd0g/merlin/releases/latest/download/merlinServer-Linux-x64.7z
    dest: /tmp/
    mode: '0755'
    validate_certs: true
  when: merlin_check.stat.exists == false

- name: MERLIN - Unzip Merlin 7z archive
  ansible.builtin.command: "7z x /tmp/merlinServer-Linux-x64.7z -o'/opt/merlin/' -p'merlin'"
  when: merlin_check.stat.exists == false

## Pre-compiled Merlin Agent binary files are distributed with the server download in the /opt/merlin/data/bin/ directory
