---
- name: REDPOINT NSE - Git clone the Redpoint repo
  ansible.builtin.git:
    repo: https://github.com/digitalbond/Redpoint
    dest: "/tmp/Redpoint"

- name: REDPOINT NSE - Register all .nse files
  ansible.builtin.find:
    paths: "/tmp/Redpoint/"
    patterns: "*.nse"
  register: redpoint_nse_files

- name: REDPOINT NSE - Move Redpoint nse scripts to nmap scripts dir
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "/usr/share/nmap/scripts/{{ item.name }}"
    owner: "{{ kali_user }}"
    group: "{{ kali_user }}"
  with_items: "{{ redpoint_nse_files.files }}"
