---
- name: RITA - Pull latest RITA Docker image
  community.docker.docker_image:
    name: quay.io/activecm/rita
    source: pull
  register: rita_image

## export CONIFG=/path/to/your/rita/config.yaml
## export LOGS=/path/to/your/zeek/logs
## docker-compose run --rm rita import /logs your-dataset
