---
- name: RUST - Install Rust dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - libssl-dev
    state: present

- name: RUST - Check that Rustc does not already exist
  ansible.builtin.stat:
    path: /home/{{ kali_user }}/.cargo/bin/rustc
  register: rust_check
  check_mode: false

- name: RUST - Download Rust install script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    owner: "{{ kali_user }}"
    mode: '0755'
    force: 'yes'
  when: rust_check.stat.exists == false

- name: RUST - install Rust and Cargo
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
  when: rust_check.stat.exists == false
  become: false

## source "$HOME/.cargo/env"
