---
- name: RUSTSCAN - Pull latest rustscan Docker image
  community.docker.docker_image:
    name: rustscan/rustscan:latest
    source: pull
  register: rustscan_image

# docker run -it --rm --name rustscan rustscan/rustscan:latest <rustscan arguments here> <ip address to scan>

# alias rustscan='docker run -it --rm --name rustscan rustscan/rustscan:latest'
