---
- name: RUST - Install Rust dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - libssl-dev
    state: present

- name: RUST - Check that cargo does not already exist
  ansible.builtin.shell: command -v cargo
  register: cargo_check
  check_mode: false
  ignore_errors: yes
  become: false

- name: RUST - Download Rust install script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    owner: "{{ kali_user }}"
    mode: '0755'
    force: 'yes'
  when: cargo_check is failed

- name: RUST - install Rust and Cargo
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
  when: cargo_check is failed

## source "$HOME/.cargo/env"
