---
- name: SHARPCOLLECTION - Create SharpCollection directory
  ansible.builtin.file:
    path: /usr/share/sharpcollection/
    state: directory

- name: SHARPCOLLECTION - Download select SharpCollection executables
  ansible.builtin.get_url:
    url: https://github.com/Flangvik/SharpCollection/raw/master/NetFramework_4.7_Any/{{ item.name }}
    dest: /usr/share/sharpcollection/
    mode: '0755'
    validate_certs: true
  with_items: "{{ sharpcollection_exes }}"
