---
- name: WORDLISTS - Check that Rockyou has not already been extracted
  ansible.builtin.stat:
    path: /usr/share/wordlists/rockyou.txt
  register: rockyou_check
  check_mode: false

- name: WORDLISTS - Unzip Rockyou gzip archive
  ansible.builtin.command: gunzip /usr/share/wordlists/rockyou.txt.gz
  when: rockyou_check.stat.exists == false
