---
- name: WORDLISTS - Check that Rockyou has not already been extracted
  ansible.builtin.stat:
    path: /usr/share/wordlists/rockyou.txt
  register: rockyou_check
  check_mode: false

- name: WORDLISTS - Unzip Rockyou gzip archive
  ansible.builtin.unarchive:
    src: /usr/share/wordlists/rockyou.txt.gz
    dest: /usr/share/wordlists/rockyou.txt
    remote_src: yes
    extra_opts: "-z"
    format: "gzip"
  when: rockyou_check.stat.exists == false
